apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://mydocctor.online"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - mydocctor.online
    secretName: mydocctor-tls
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mydocctorfrontend-service
            port:
              number: 5173
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: mydocctor-auth-service
            port:
              number: 4001
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: mydocctor-user-service
            port:
              number: 4002
      - path: /api/doctor
        pathType: Prefix
        backend:
          service:
            name: mydocctor-doctor-service
            port:
              number: 4003
      - path: /api/appointment
        pathType: Prefix
        backend:
          service:
            name: mydocctor-appointment-service
            port:
              number: 4005
      - path: /api/payments
        pathType: Prefix
        backend:
          service:
            name: mydocctor-payments-service
            port:
              number: 4006
      - path: /api/chat
        pathType: Prefix
        backend:
          service:
            name: mydocctor-chat-service
            port:
              number: 4007
      - path: /api/notification
        pathType: Prefix
        backend:
          service:
            name: mydocctor-notification-service
            port:
              number: 4008
