apiVersion: v1
kind: Service
metadata:
  name:  mydocctor-notification-service
spec:
  selector:
    app: notification-service
  ports:
  - name:  notification-service
    protocol: TCP
    port:  4008
    targetPort: 4008