apiVersion: v1
kind: Service
metadata:
  name:  mydocctor-payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name:  payment-service
    protocol: TCP
    port:  4006
    targetPort: 4006