apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "4001"
  MONGO_URL: mongodb+srv://arjunpchr:YFMQ6VWOm32SfAlm@cluster0.w5qzsxa.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp
  EMAIL: mydocctor@gmail.com
  PASSWORD: sihc ugrp vhrk cjdx
  ACCESS_TOKEN_SECRET: jC1XHDWUgt6!$ZG%pN6^yL3E@5uV*JcFk29L@2Tr5XqkzGy
