apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydocctor-appointment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydocctor-appointment-service
  template:
    metadata:
      labels:
        app: mydocctor-appointment-service
    spec:
      containers:
      - name: mydocctor-appointment-service
        image: arjun164/mydocctor-appointment:latest
        ports:
        - containerPort: 4005
        envFrom:
        - configMapRef:
            name: appointment-service-config 
---
apiVersion: v1
kind: Service
metadata:
  name: mydocctor-appointment-service
spec:
  selector:
    app: mydocctor-appointment-service
  ports:
  - protocol: TCP
    port: 4005
    targetPort: 4005