apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydocctor-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydocctor-auth-service
  template:
    metadata:
      labels:
        app: mydocctor-auth-service
    spec:
      containers:
      - name: mydocctor-auth-service
        image: arjun164/mydocctor-auth:latest
        ports:
        - containerPort: 4001
        envFrom:
        - configMapRef:
            name: auth-service-config
      imagePullSecrets:
       - name: registry-secret      
---
apiVersion: v1
kind: Service
metadata:
  name: mydocctor-auth-service
spec:
  selector:
    app: mydocctor-auth-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001