apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydocctor-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydocctor-chat-service
  template:
    metadata:
      labels:
        app: mydocctor-chat-service
    spec:
      containers:
      - name: mydocctor-chat-service
        image: arjun164/mydocctor-notification:latest
        ports:
        - containerPort: 4008
        envFrom:
        - configMapRef:
            name: chat-config 
---
apiVersion: v1
kind: Service
metadata:
  name: mydocctor-chat-service
spec:
  selector:
    app: mydocctor-chat-service
  ports:
  - protocol: TCP
    port: 4008
    targetPort: 4008
