apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydocctor-payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydocctor-payment-service
  template:
    metadata:
      labels:
        app: mydocctor-payment-service
    spec:
      containers:
      - name: mydocctor-payment-service
        image: arjun164/mydocctor-payment:latest
        ports:
        - containerPort: 4006
        envFrom:
        - configMapRef:
            name: payment-config 
---
apiVersion: v1
kind: Service
metadata:
  name: mydocctor-payment-service
spec:
  selector:
    app: mydocctor-payment-service
  ports:
  - protocol: TCP
    port: 4006
    targetPort: 4006